variables:
    SCHEDULER_PARAMETERS: "-n 4 -p nitrogen"
    USER: legit
    PYADFHOME: $CI_BUILDS_DIR/$CI_PROJECT_PATH
    PYADF_NPROC: 4
    CONDA_MODULE_LOAD: python/anaconda3-2022.5
    CONDA_ENV: "pipeline_${CI_PIPELINE_ID}"
    CONDA_ENV_BASE: ci_pyadf

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_PIPELINE_SOURCE == "web"'

default:
    before_script:
        - hostname
        - . /usr/share/modules/init/bash
        - . /usr/share/modules/init/setup
        - module load $CONDA_MODULE_LOAD
        - conda activate $CONDA_ENV
        - module load locvib/master-20221116
        - export PYADF_NPROC
        - export PYTHONUNBUFFERED=1
        - export PYADF_TEST_LINEBREAKS=1

stages:
    - build
    - general
    - openbabel
    - rdkit
    - obfree
    - cleanup

install_pyadf:
    before_script:
        - hostname
        - . /usr/share/modules/init/bash
        - . /usr/share/modules/init/setup
        - module load locvib/master-20221116
        - module load $CONDA_MODULE_LOAD
        - conda env remove --name $CONDA_ENV --yes
        - conda env create --name $CONDA_ENV --file $PYADFHOME/src/pyadf/test/test_env.yml
        - conda activate $CONDA_ENV
    tags:
        - nodes
    stage: build
    script:
        - pip install .

doctests-openbabel:
    tags:
        - nodes
    stage: general
    needs: ["install_pyadf"]
    script:
        - test_pyadf --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=doctests

doctests-rdkit:
    tags:
        - nodes
    stage: general
    needs: ["install_pyadf"]
    script:
        - test_pyadf --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=doctests

unittests:
    tags:
        - nodes
    stage: general
    needs: ["install_pyadf"]
    script:
        - test_pyadf --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=unittests

misc:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --noturbomole --noorca --nodirac --nodalton --noadf --nonwchem --noespresso --nomolcas --nodoctests --nounittests

turbomole:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=turbomole --nodoctests --nounittests

orca:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --test=orca --nodoctests --nounittests

dirac:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=dirac --nodoctests --nounittests

dalton:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=dalton --nodoctests --nounittests

adf:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=adf --nodoctests --nounittests

nwchem:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=nwchem --nodoctests --nounittests

espresso:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=espresso --nodoctests --nounittests

molcas:
    tags:
        - nodes
    stage: openbabel
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=openbabel --tests=molcas --nodoctests --nounittests

misc_rd:
    tags:
        - nodes
    stage: rdkit  
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --noturbomole --noorca --nodirac --nodalton --noadf --nonwchem --noespresso --nomolcas --nodoctests --nounittests

turbomole_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=turbomole --nodoctests --nounittests

orca_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --test=orca --nodoctests --nounittests

dirac_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=dirac --nodoctests --nounittests

dalton_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=dalton --nodoctests --nounittests

adf_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=adf --nodoctests --nounittests

nwchem_rd:
    tags:
        - nodes
    stage: rdkit  
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=nwchem --nodoctests --nounittests

espresso_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=espresso --nodoctests --nounittests

molcas_rd:
    tags:
        - nodes
    stage: rdkit
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=rdkit --tests=molcas --nodoctests --nounittests

misc_obfree:
    tags:
        - nodes
    stage: obfree  
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --noturbomole --noorca --noadf --nodirac --nodalton --nonwchem --noespresso --nomolcas --nodoctests --nounittests

turbomole_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=turbomole --nodoctests --nounittests

orca_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --test=orca --nodoctests --nounittests

dirac_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=dirac --nodoctests --nounittests

dalton_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=dalton --nodoctests --nounittests

adf_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=adf --nodoctests --nounittests

nwchem_obfree:
    tags:
        - nodes
    stage: obfree  
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=nwchem --nodoctests --nounittests

espresso_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=espresso --nodoctests --nounittests

molcas_obfree:
    tags:
        - nodes
    stage: obfree
    needs: ["unittests"]
    script:
        - test_pyadf --keep --timings --noopenbabel --jobrunnerconf $PYADFHOME/src/pyadf/test/test_pyadf.conf --molclass=obfree --tests=molcas --nodoctests --nounittests

cleanup_conda:
    before_script:
        - hostname
        - . /usr/share/modules/init/bash
        - . /usr/share/modules/init/setup
        - module load locvib/master-20221116
        - module load $CONDA_MODULE_LOAD
    tags:
        - nodes
    stage: cleanup
    when: always
    script:
        - conda env remove --name $CONDA_ENV --yes
