#!/usr/bin/env python
# encoding: utf-8
"""
remove_myfiles

Script to remove myfiles argument from pyadf scripts.

This file is part of PyADF
"""

from optparse import OptionParser
import shutil
import re

def main():
    parser = OptionParser(usage="usage: %prog [options] files")
    (options, args) = parser.parse_args()

    regexp1 = re.compile(r'job\s*\((?P<arg1>.*?),')
    regexp2 = re.compile(r'job.__init__\s*\((?P<arg1>.*?),(?P<arg2>.*?),')

    def repl1 ( m ):
        arg1 = m.group('arg1').strip()

        if arg1 == 'myfiles' or arg1 == 'None':
            result = 'job('
        else :
            result = m.group()

        print m.group(), " --> ", result

        return result

    def repl2 ( m ):
        arg1 = m.group('arg1').strip()
        arg2 = m.group('arg2').strip()

        if 'files' in arg2 or arg2 == 'None' :
            result = "job.__init__ (self,"
        else:
            result = m.group()
            
        print m.group(), " --> ", result
        
        return result

    for f in args :
        print "Processing file ", f
        shutil.copyfile(f, f+'.bak')
        
        fd = open(f, 'r')
        content = fd.read()
        fd.close()
        
        content = regexp1.sub(repl1, content)
        content = regexp2.sub(repl2, content)
        
        fd = open(f, 'w')
        fd.write(content)
        fd.close()

if __name__ == '__main__':
    main()

